### PR TITLE
Fix install instructions

### PR DESCRIPTION
**Pull request by bart-webleads**
You need to enable the module, before you can use it...

### CODE REVIEW

**Comment by peterjaap** [comment]
`setup:upgrade` takes care of that.

**Comment by bart-webleads** [comment]
Nope. Does not...

**Comment by peterjaap** [comment]
@bart-webleads in that case there might be something wrong with your install. But `setup:upgrade` definitely enables plugins in a normal install.

**Comment by peterjaap** [comment]
Here's the line that's responsible for enabling new extensions; https://github.com/magento/magento2/blob/0763e060d1e491385280c82ac9f951b1a8b1fcfe/setup/src/Magento/Setup/Model/Installer.php#L461

**Comment by bart-webleads** [comment]
Hmm, strange that it did not enable it in my project...
Thanks for the info and have a great day.


Met vriendelijke groet,
Bart Lagerweij | ***@***.***



Op do 24 mrt. 2022 om 09:42 schreef Peter Jaap Blaakmeer <
***@***.***>:

**Pull request closed without merging**
