### PR TITLE
Update RegenerateProductUrl.php

### PR DESCRIPTION
**Pull request by mokadev**
you can't just regenerate a product or a group of product .

### CODE REVIEW

**Comment by peterjaap** [comment]
@mokadev I don't understand this, what doesn't work exactly and why would this fix it?

**Comment by mokadev** [comment]
@peterjaap 

When you want to regenerate an url for some product ids this statement is always true:

`if (!is_null($productIds))`


but then you filter the collection on all product ids of the catalog with this :

`$productIds = $collection->getAllIds();
$collection->addIdFilter($productIds);`

`$collection->getAllIds()` returns all the products even you specified a product id

**Comment by peterjaap** [comment]
@mokadev what is the command you're running on the CLI?

**Comment by mokadev** [comment]
@peterjaap 

`php bin/magento regenerate:product:url -s1 24568 24569`

24568 & 24569 are two product ids

**Comment by peterjaap** [comment]
Thanks, I tested it and made a small adjustment. Works now.

**Pull request merged**
